// Mock data for frontend-only deployment
// This matches the exact structure from server/storage.ts and shared/schema.ts
export const mockProducts = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "Experience crystal-clear audio with active noise cancellation and 30-hour battery life. Premium comfort for all-day wear.",
    price: "299.99",
    originalPrice: "399.99",
    category: "electronics",
    image: "/images/Premium_headphones_product_shot_b248cf9f.png",
    images: [
      "/images/Premium_headphones_product_shot_b248cf9f.png",
      "/images/Premium_headphones_product_shot_b248cf9f.png",
      "/images/Premium_headphones_product_shot_b248cf9f.png",
      "/images/Premium_headphones_product_shot_b248cf9f.png"
    ],
    inStock: true,
    rating: "4.8",
    reviewCount: 324,
    specifications: "Bluetooth 5.0, Active Noise Cancellation, 30-hour battery, Premium leather ear cups",
    featured: true,
  },
  {
    id: "2",
    name: "Classic Leather Watch",
    description: "Timeless elegance meets precision engineering. Swiss-made automatic movement with genuine leather strap.",
    price: "459.00",
    originalPrice: "599.00",
    category: "fashion",
    image: "/images/Luxury_watch_product_image_45f1b7ad.png",
    images: [
      "/images/Luxury_watch_product_image_45f1b7ad.png",
      "/images/Luxury_watch_product_image_45f1b7ad.png",
      "/images/Luxury_watch_product_image_45f1b7ad.png",
      "/images/Luxury_watch_product_image_45f1b7ad.png"
    ],
    inStock: true,
    rating: "4.9",
    reviewCount: 156,
    specifications: "Swiss automatic movement, Sapphire crystal, Water resistant 50m, Genuine leather strap",
    featured: true,
  },
  {
    id: "3",
    name: "Midnight Blue Smartphone",
    description: "Flagship performance with stunning OLED display and professional-grade camera system. The ultimate mobile experience.",
    price: "899.99",
    originalPrice: "1099.99",
    category: "electronics",
    image: "/images/Smartphone_product_photography_c0327e48.png",
    images: [
      "/images/Smartphone_product_photography_c0327e48.png",
      "/images/Smartphone_product_photography_c0327e48.png",
      "/images/Smartphone_product_photography_c0327e48.png",
      "/images/Smartphone_product_photography_c0327e48.png"
    ],
    inStock: true,
    rating: "4.7",
    reviewCount: 892,
    specifications: "6.5-inch OLED display, Triple camera system, 5G connectivity, 128GB storage",
    featured: true,
  },
  {
    id: "4",
    name: "Premium Leather Laptop Bag",
    description: "Handcrafted Italian leather with premium hardware. Perfect for professionals who demand quality and style.",
    price: "189.99",
    originalPrice: null,
    category: "accessories",
    image: "/images/Leather_bag_product_shot_22389871.png",
    images: [
      "/images/Leather_bag_product_shot_22389871.png",
      "/images/Leather_bag_product_shot_22389871.png",
      "/images/Leather_bag_product_shot_22389871.png",
      "/images/Leather_bag_product_shot_22389871.png"
    ],
    inStock: true,
    rating: "4.6",
    reviewCount: 234,
    specifications: "Genuine Italian leather, Fits 15-inch laptops, Multiple compartments, YKK zippers",
    featured: true,
  },
  {
    id: "5",
    name: "Minimalist Ceramic Mug",
    description: "Artisan-crafted ceramic mug with perfect ergonomics. Microwave and dishwasher safe.",
    price: "24.99",
    originalPrice: null,
    category: "lifestyle",
    image: "/images/Ceramic_mug_product_image_c9c84494.png",
    images: [
      "/images/Ceramic_mug_product_image_c9c84494.png",
      "/images/Ceramic_mug_product_image_c9c84494.png",
      "/images/Ceramic_mug_product_image_c9c84494.png",
      "/images/Ceramic_mug_product_image_c9c84494.png"
    ],
    inStock: true,
    rating: "4.5",
    reviewCount: 567,
    specifications: "12oz capacity, Food-safe glaze, Microwave safe, Dishwasher safe",
    featured: false,
  },
  {
    id: "6",
    name: "Modern LED Desk Lamp",
    description: "Adjustable brightness with multiple color temperatures. Perfect for work and relaxation.",
    price: "79.99",
    originalPrice: "99.99",
    category: "lifestyle",
    image: "/images/Desk_lamp_product_image_e2ba729b.png",
    images: [
      "/images/Desk_lamp_product_image_e2ba729b.png",
      "/images/Desk_lamp_product_image_e2ba729b.png",
      "/images/Desk_lamp_product_image_e2ba729b.png",
      "/images/Desk_lamp_product_image_e2ba729b.png"
    ],
    inStock: true,
    rating: "4.7",
    reviewCount: 423,
    specifications: "Dimmable LED, 5 color temperatures, Touch controls, USB charging port",
    featured: false,
  },
  {
    id: "7",
    name: "Performance Running Shoes",
    description: "Engineered for speed and comfort. Responsive cushioning meets breathable design.",
    price: "149.99",
    originalPrice: null,
    category: "fashion",
    image: "/images/Running_shoes_product_shot_674f016b.png",
    images: [
      "/images/Running_shoes_product_shot_674f016b.png",
      "/images/Running_shoes_product_shot_674f016b.png",
      "/images/Running_shoes_product_shot_674f016b.png",
      "/images/Running_shoes_product_shot_674f016b.png"
    ],
    inStock: true,
    rating: "4.8",
    reviewCount: 678,
    specifications: "Breathable mesh upper, Responsive foam, Carbon fiber plate, Reflective details",
    featured: false,
  },
  {
    id: "8",
    name: "Aviator Sunglasses",
    description: "Classic design with polarized lenses. UV400 protection and premium metal frame.",
    price: "129.00",
    originalPrice: "179.00",
    category: "accessories",
    image: "/images/Sunglasses_product_image_9e5d45c8.png",
    images: [
      "/images/Sunglasses_product_image_9e5d45c8.png",
      "/images/Sunglasses_product_image_9e5d45c8.png",
      "/images/Sunglasses_product_image_9e5d45c8.png",
      "/images/Sunglasses_product_image_9e5d45c8.png"
    ],
    inStock: true,
    rating: "4.6",
    reviewCount: 289,
    specifications: "Polarized lenses, UV400 protection, Metal frame, Includes case and cloth",
    featured: false,
  },
  {
    id: "9",
    name: "Modern Travel Backpack",
    description: "Water-resistant design with laptop compartment. Perfect for urban explorers and digital nomads.",
    price: "99.99",
    originalPrice: null,
    category: "accessories",
    image: "/images/Backpack_product_photography_1692a3f7.png",
    images: [
      "/images/Backpack_product_photography_1692a3f7.png",
      "/images/Backpack_product_photography_1692a3f7.png",
      "/images/Backpack_product_photography_1692a3f7.png",
      "/images/Backpack_product_photography_1692a3f7.png"
    ],
    inStock: true,
    rating: "4.7",
    reviewCount: 512,
    specifications: "Water-resistant fabric, Laptop compartment (15-inch), USB charging port, Anti-theft pocket",
    featured: false,
  },
  {
    id: "10",
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with 360-degree sound and waterproof design.",
    price: "149.99",
    originalPrice: null,
    category: "electronics",
    image: "/images/Hero_lifestyle_speaker_image_d365e228.png",
    images: [
      "/images/Hero_lifestyle_speaker_image_d365e228.png",
      "/images/Hero_lifestyle_speaker_image_d365e228.png",
      "/images/Hero_lifestyle_speaker_image_d365e228.png",
      "/images/Hero_lifestyle_speaker_image_d365e228.png"
    ],
    inStock: true,
    rating: "4.7",
    reviewCount: 203,
    specifications: "360-degree sound, Waterproof design, 12-hour battery, Voice assistant compatible",
    featured: false,
  },
];

export const mockCartItems: any[] = [];
export const mockOrders: any[] = [];
